### ISSUE TITLE
Feature idea: add i18n support for CSS texts

### ISSUE THREAD

**Issue by robertharm** [elmarquis/Leaflet.GestureHandling#3]
First thanks a lot for creating this plugin - it is great that there is finally a solution to the dragging issue on mobile devices for leaflet.js!

I wonder if the code could be enhanced to also support different languages for the text which is currently added in the CSS file via content: '...' attribute? I search for possible solution and found this: https://stackoverflow.com/questions/29743156/reading-internationalized-content-from-css-file/29743624#29743624

Do you think this could be a possible approach to add i18n support to your plugin?

**Comment by elmarquis** [comment]
This is an excellent suggestion, one I hadn't quite figured out how best to implement. I really like the suggested approach as it utilises the html lang attribute. 
I'll look into getting something like this implemented over the next week or so. 
Thanks again.

**Comment by elmarquis** [comment]
@robertharm I've create an internationalisation branch. (Still in progress)
Take a look and let me know if this looks close to what you had in mind. 

**src/js/language-content.js** - Contributors can add entries for each language here. When compiled with grunt it is concatenated into the main plugin file leaflet-gesture-handling.js in the dist folder. 
I'll probably look at getting rid of the mac/pc variations and just have a single entry where I replace the Ctrl+ for CMD+. 

**leaflet-gesture-handling.js**
- To identify language I'm using: navigator.languages rather than html attribute, that way I'm getting the users settings rather than the pages. 
- If a language variation such as en-US is in use, but no content found, it makes an attempt to find an entry matching en instead. 
- If all else fails it defaults to English.

**Comment by robertharm** [comment]
thanks for the quick update - looks quite promising! An idea to get as many localisations as possible: switching the browser to another default language and opening e.g. https://developers.google.com/maps/documentation/javascript/interaction afterwards to find out which translated texts users are used to when panning the map on mobiles.

**Comment by tgelz** [comment]
I would go for the usual Leaflet solution and set the text via JavaScript. The according text would be set via an option, just like the Leaflet zoom control, for instance.

https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Zoom.js#L27

Especially because in our case we have settings that allow the user to force a certain language, regardless of browser settings, and passing the translation of the set language to the plugin is the only way to respect those choices.

**Comment by elmarquis** [comment]
Hmm better idea actually. 
I would use an official cdn hosted language file which can be overridden by the users custom one if they please. 

`options: {
    defaultLanguage: "en", //Used if no suitable language is found in the languagesFile
    languageSrc: "/data/mycustomlanguagefile.json" //defaults to the official language file hosted on a cdn url
}`

**Comment by robertharm** [comment]
I think your first idea would actually be more usable (using `CustomTranslation: [ ... ]`) as this allows more flexibility in e.g. loading custom translations for WordPress, where translation strings are often stored globally in a .mo file and not in a separate .json file.

**Comment by robertharm** [comment]
@elmarquis I wonder if you found time lately for this enhancement. Can we help here somehow?

**Comment by elmarquis** [comment]
Hi @robertharm Just finished some stuff off and pushed. There should now be 52 language translations available in the internationalisation code branch. It just sets automatically via browser lang. 
I've not merged to master yet as I'll need to do some more testing. But feel free to pull it and see how it goes. 

Still to do: pass in language overrides as options

**Comment by elmarquis** [comment]
Alright. Leave it with me and I'll take a look at the other solution in the next couple of days. Sorry for being a bit unresponsive. New baby arrived a couple of months ago and it's all been a bit erratic since. 
Slowly getting time back for my code projects. 

In case it's still of use the auto translations I added can all be found in the internationalisation branch. 
https://github.com/elmarquis/Leaflet.GestureHandling/tree/internationalisation and already contains the translations as seen in G-example.

**Comment by robertharm** [comment]
nothing to apologize for - I am having kids too & fully understand, lack of sleep can be exhausting ;-)

**Comment by elmarquis** [comment]
Pleased to announce the ability to supply custom text as a map option has now been added and merged into master. 

Details in readme file. 

Let me know if there's any issues.

**Comment by robertharm** [comment]
Thanks a lot for the update - first tests look good so far. 

As we plan to only use custom texts only in the long run, we are still looking for a way to optimize the file size without having to fork your plugin (without all translations, the size of your plugin would only be 5k vs 40k).

Nevertheless thanks for adding this feature - if you´re interested in a free license of our plugin as mentioned before, please get in contact via https://mapsmarker.com/contact

**Comment by elmarquis** [comment]
Great. 
Moving the language files to something on demand for smaller file sizes is something I'll be looking into next.

**Comment by elmarquis** [comment]
Closing this ticket and moving the language files to on demand discussion to it's own ticket #17
