### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dragging' of undefined  in Chrome-Mobile Device view

### ISSUE THREAD

**Issue by meeeeeGeeka** [elmarquis/Leaflet.GestureHandling#4]
Hi!

When i switch to the mobile device view in google chrome on windows (switch to the "examine"-Toolbar, then use "Toggle Device Toolbar" (Ctrl + Shift + M)) i get the following error message:

Uncaught TypeError: Cannot read property 'dragging' of undefined
    at HTMLDivElement._handleTouch (leaflet-gesture-handling.min.js:1)
_handleTouch @ leaflet-gesture-handling.min.js:1

It still works (though it IS a little buggy on mobile devices). but i'm wondering if this also happens on chrome on android phones.

**Comment by elmarquis** [comment]
Thanks. 
I found using chrome desktop to emulate mobile device doesn't really translate the touch actions the same as an actual device would. I don't believe real devices are triggering this same error. 
All the same, thanks for flagging. I'll have another look and if necessary wrap some better handling around that.

**Comment by elmarquis** [comment]
This issue should now be fixed in branch v1.1.2 which I'll be merging into master once I've finished ironing out a few bugs. 
Thanks for reporting, it did turn out to be causing some issues. 
Things should be a lot more stable on mobile devices now, although SamsungBrowser is still giving me some zoom issues. 
Chrome (Android/iOS) and Safari(iOs) are working well for me.

**Comment by elmarquis** [comment]
Fix now merged into master. Marking this as closed.
