### ISSUE TITLE
Does not work with leaflet 1.7.1

### ISSUE THREAD

**Issue by mvolland** [elmarquis/Leaflet.GestureHandling#56]
I have updated Leaflet to version 1.7.1 and now Leaflet.GestureHandling has no functionality. The message does not come and you can scroll on the map.

**Comment by j0Shi82** [comment]
It's because leaflet in 1.7.x has slightly changed the way it handles the [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event) `mousewheel` event. In 1.6.x it would switch to the `wheel` event, but now it just passes `mousewheel`, which is non-standard and not supported on modern browsers.

tl;dr: leaflet-gesture-handling has to switch from `mousewheel` to `wheel`.

**Comment by j0Shi82** [comment]
Since I'm not sure this repo is still actively maintained you can use

```
"leaflet-gesture-handling": "j0Shi82/Leaflet.GestureHandling#9d81d7b25e8b158ff56699931613edaa9e2239cf",
```

in the meantime. Please note that this is a one-time fix for now. I do not plan to maintain this plugin myself.

**Comment by elmarquis** [comment]
Confirming that this has now also been published to NPM
