### ISSUE TITLE
after double click on the map i can move inside the map with one finger

### ISSUE THREAD

**Issue by cn-tools** [elmarquis/Leaflet.GestureHandling#6]
### my system
Android 7.0

### tested browser
* Firefox
* Android standard browser

### aditional info
i have also this problem on windows 10 with google chrome Version 66.0.3359.181 (Offizieller Build) (64-Bit) and active developer tools

**Comment by elmarquis** [comment]
Thanks for reporting. Can confirm I’m also experiencing this on iOS safari and chrome.

**Comment by elmarquis** [comment]
I've written a fix for this in branch v1.1.2. Wondering if you could confirm it's working correctly for you before I merge into master.

**Comment by cn-tools** [comment]
thx 4 your fast response and branch!

### No marker
it works perfect!!

### With marker
Now i can move the map with one finger, if i touch the marker direct

### Here my leaflet JS
```
var LLat = 48.208446;
var LLong = 16.375966;

var map = L.map('map', {
	dragging: !L.Browser.mobile,
	gestureHandling: true,
	scrollWheelZoom: false
}).setView([LLat, LLong], 12);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([LLat, LLong]).addTo(map)
  .bindPopup('Hello Vienna')
  .openPopup();

```
I hope you can reproduce this also.

**Comment by elmarquis** [comment]
Thanks. Turns out there was a bit of cross platform touch interaction stuff I had to debug. These should now be resolved (in same branch) including the issue where you could scroll the map with one finger. (Samsung Browser still has some pinch zoom issues, but chrome, safari, firefox appear to be working fine now)

I'm not sure what to do about the markers. When the map is stationary I want users to be able to freely click markers and popups without getting warning overlays. It's not always easy to differentiate between dragging and clicking across different touch devices. 

I was tempted to do leave it as it is. I guess the edge case would be where a map has a huge cluster of markers and the user can't get a clean bit of map to drag on to scroll the page. 

Will have a think about this one.

**Comment by cn-tools** [comment]
Thanks! I will test it in the next few days and give feedback.

**Comment by elmarquis** [comment]
Confident the last update fixed this issue. Marking as resolved.
